"""add_cost_column_to_products

Revision ID: affc34510273
Revises: 9b7835f6d237
Create Date: 2026-02-23 15:54:12.381457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'affc34510273'
down_revision: Union[str, None] = '9b7835f6d237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_drift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_drift_detected_at'))
        batch_op.drop_index(batch_op.f('ix_model_drift_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_model_drift_tenant_id'))

    op.drop_table('model_drift')
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_performance_evaluation_date'))
        batch_op.drop_index(batch_op.f('ix_model_performance_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_model_performance_tenant_id'))

    op.drop_table('model_performance')
    with op.batch_alter_table('retraining_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retraining_jobs_model_type'))
        batch_op.drop_index(batch_op.f('ix_retraining_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_retraining_jobs_tenant_id'))

    op.drop_table('retraining_jobs')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_is_active'))
        batch_op.drop_index(batch_op.f('ix_model_versions_model_type'))
        batch_op.drop_index(batch_op.f('ix_model_versions_status'))
        batch_op.drop_index(batch_op.f('ix_model_versions_tenant_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sentiment_label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('sentiment_label')
        batch_op.drop_column('review_text')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('cost')

    op.create_table('model_versions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('framework', sa.VARCHAR(length=100), nullable=True),
    sa.Column('algorithm', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hyperparameters', sqlite.JSON(), nullable=True),
    sa.Column('model_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('model_size_mb', sa.FLOAT(), nullable=True),
    sa.Column('training_data_size', sa.INTEGER(), nullable=True),
    sa.Column('training_duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('trained_at', sa.DATETIME(), nullable=True),
    sa.Column('trained_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('archived_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_model_type'), ['model_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_is_active'), ['is_active'], unique=False)

    op.create_table('retraining_jobs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('trigger_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source_model_version_id', sa.CHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('training_config', sqlite.JSON(), nullable=True),
    sa.Column('training_data_size', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('new_model_version_id', sa.CHAR(length=36), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['new_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['source_model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retraining_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retraining_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retraining_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_retraining_jobs_model_type'), ['model_type'], unique=False)

    op.create_table('model_performance',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('evaluation_date', sa.DATETIME(), nullable=False),
    sa.Column('evaluation_period_start', sa.DATETIME(), nullable=True),
    sa.Column('evaluation_period_end', sa.DATETIME(), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.Column('predictions_count', sa.INTEGER(), nullable=True),
    sa.Column('actuals_count', sa.INTEGER(), nullable=True),
    sa.Column('baseline_metrics', sqlite.JSON(), nullable=True),
    sa.Column('improvement_over_baseline', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_performance_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_performance_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_performance_evaluation_date'), ['evaluation_date'], unique=False)

    op.create_table('model_drift',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('detected_at', sa.DATETIME(), nullable=True),
    sa.Column('drift_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('metric_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('baseline_value', sa.FLOAT(), nullable=True),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.Column('drift_percentage', sa.FLOAT(), nullable=True),
    sa.Column('is_significant', sa.BOOLEAN(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('alert_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_sent_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('resolution_notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('drift_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_drift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_drift_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_drift_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_drift_detected_at'), ['detected_at'], unique=False)

    # ### end Alembic commands ###
